version: 2

sources:
  - name: weather_source         
    schema: raw_data             # Tu dataset real en GCP
    tables:
      - name: historical_weather   # Tu tabla real en GCP
        description: "Datos climáticos históricos crudos extraídos de la API."

models:
  - name: stg_weather            # El nombre de tu archivo SQL (sin el .sql)
    description: "Modelo staging con los datos climáticos limpios y estandarizados."
    columns:
      - name: observation_date
        description: "Fecha de la observación meteorológica (casteada desde la columna time)."
        tests:
          - unique               # Test: Verifica que no haya fechas duplicadas
          - not_null             # Test: Verifica que la fecha no venga vacía
      - name: max_temperature_c
        description: "Temperatura máxima en grados Celsius."
      - name: min_temperature_c
        description: "Temperatura mínima en grados Celsius."
      - name: total_precipitation_mm
        description: "Precipitación total en milímetros."
      - name: latitude
        description: "Latitud de la ubicación."
      - name: longitude
        description: "Longitud de la ubicación."
      - name: extraction_timestamp
        description: "Fecha y hora exacta de la extracción."